[workspace]
resolver = "2"
members = [
    "lib",
    "egui-sdl2-event-example"
]

[workspace.dependencies]
sdl2 = { version= "0.38.0", features = ["raw-window-handle"] }
egui = { version = "0.33.3" }
egui-wgpu = {version =  "0.33.3" }
