[package]
name = "egui-sdl2-event-example"
edition = "2021"

[dependencies]
sdl2 = { version= "0.38.0", features = ["raw-window-handle"] }
egui-sdl2-event = { path = "../lib" }
egui-wgpu = {version =  "0.31.1" }
egui = "0.31.1"
pollster = "0.2.5"
