[package]
name = "egui-sdl2-event-example"
edition = "2021"

[dependencies]
sdl2.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-sdl2-event = { path = "../lib" }
pollster = "0.2.5"
