[package]
name = "egui-sdl2-event-example"
edition = "2021"

[dependencies]
sdl2.workspace = true
egui.workspace = true
egui-sdl2-event = { path = "../lib" }
egui-wgpu = {version =  "0.32.3" }
pollster = "0.2.5"
